In [64]:
from flatten_json import flatten
import pandas as pd
import sys
import json
from pandas.io.json import json_normalize
import csv

In [3]:
with open('362073_20191022.json') as access_json:
    read_content = json.load(access_json)

aw = read_content['root']['leasedArea']

In [54]:
# flat = flatten_json(aw)
df = json_normalize(aw)
df.columns = df.columns.str.replace(".", "_")
df

,grossInternalArea_area_unit_metaData_lastUpdated,grossInternalArea_area_unit_metaData_id,grossInternalArea_area_unit_data,grossInternalArea_area_value_metaData_lastUpdated,grossInternalArea_area_value_metaData_id,grossInternalArea_area_value_data,netInternalArea_area_unit_metaData_lastUpdated,netInternalArea_area_unit_metaData_id,netInternalArea_area_unit_data,netInternalArea_area_value_metaData_lastUpdated,...,areaStartDate_date_metaData_lastUpdated,areaStartDate_date_metaData_id,areaStartDate_date_month,areaStartDate_date_year,areaStartDate_date_day,areaEndDate_date_metaData_lastUpdated,areaEndDate_date_metaData_id,areaEndDate_date_month,areaEndDate_date_year,areaEndDate_date_day
0,2018-12-10T11:31:21Z,83698103,10,2018-12-10T11:31:21Z,83698103,100,2018-12-10T11:31:21Z,83698107,10,2018-12-10T11:31:21Z,...,2019-06-12T15:09:12Z,83698104,07,1875,01,2019-06-12T15:09:12Z,83698105,12,2020,31
1,2019-05-07T14:37:40Z,83805392,10,2019-05-07T14:37:40Z,83805392,200,2018-12-11T08:22:07Z,83805396,10,2018-12-11T08:22:07Z,...,2019-06-12T15:09:12Z,83805389,07,1875,01,2019-06-12T15:09:12Z,83805387,12,2020,31
2,2019-05-07T14:37:47Z,83805886,10,2019-05-07T14:37:47Z,83805886,300,2018-12-11T08:59:50Z,83805888,10,2018-12-11T08:59:50Z,...,2019-06-12T15:09:12Z,83805893,07,1875,01,2019-06-12T15:09:12Z,83805885,12,2020,31
3,2019-05-07T14:37:53Z,84511744,10,2019-05-07T14:37:53Z,84511744,400,2018-12-20T12:18:06Z,84511745,10,2018-12-20T12:18:06Z,...,2019-06-12T15:09:12Z,84511741,07,1875,01,2018-12-20T12:20:26Z,84511740,12,2020,31
4,2019-05-07T14:22:04Z,88510212,10,2019-05-07T14:22:04Z,88510212,500,2019-05-07T14:21:57Z,88510213,10,2019-05-07T14:21:57Z,...,2019-06-12T15:09:12Z,88510205,07,1875,01,2019-06-12T15:09:12Z,88510207,12,2020,31
5,2019-10-09T17:22:24Z,91959769,10,2019-10-09T17:22:24Z,91959769,100,2019-10-09T17:22:24Z,91959762,10,2019-10-09T17:22:24Z,...,2019-10-09T17:22:24Z,91959761,07,1875,01,2019-10-09T17:22:24Z,91959767,12,2020,31

In [55]:
#df = "|" + df.astype(str) + '|'

In [56]:
df

,grossInternalArea_area_unit_metaData_lastUpdated,grossInternalArea_area_unit_metaData_id,grossInternalArea_area_unit_data,grossInternalArea_area_value_metaData_lastUpdated,grossInternalArea_area_value_metaData_id,grossInternalArea_area_value_data,netInternalArea_area_unit_metaData_lastUpdated,netInternalArea_area_unit_metaData_id,netInternalArea_area_unit_data,netInternalArea_area_value_metaData_lastUpdated,...,areaStartDate_date_metaData_lastUpdated,areaStartDate_date_metaData_id,areaStartDate_date_month,areaStartDate_date_year,areaStartDate_date_day,areaEndDate_date_metaData_lastUpdated,areaEndDate_date_metaData_id,areaEndDate_date_month,areaEndDate_date_year,areaEndDate_date_day
0,2018-12-10T11:31:21Z,83698103,10,2018-12-10T11:31:21Z,83698103,100,2018-12-10T11:31:21Z,83698107,10,2018-12-10T11:31:21Z,...,2019-06-12T15:09:12Z,83698104,07,1875,01,2019-06-12T15:09:12Z,83698105,12,2020,31
1,2019-05-07T14:37:40Z,83805392,10,2019-05-07T14:37:40Z,83805392,200,2018-12-11T08:22:07Z,83805396,10,2018-12-11T08:22:07Z,...,2019-06-12T15:09:12Z,83805389,07,1875,01,2019-06-12T15:09:12Z,83805387,12,2020,31
2,2019-05-07T14:37:47Z,83805886,10,2019-05-07T14:37:47Z,83805886,300,2018-12-11T08:59:50Z,83805888,10,2018-12-11T08:59:50Z,...,2019-06-12T15:09:12Z,83805893,07,1875,01,2019-06-12T15:09:12Z,83805885,12,2020,31
3,2019-05-07T14:37:53Z,84511744,10,2019-05-07T14:37:53Z,84511744,400,2018-12-20T12:18:06Z,84511745,10,2018-12-20T12:18:06Z,...,2019-06-12T15:09:12Z,84511741,07,1875,01,2018-12-20T12:20:26Z,84511740,12,2020,31
4,2019-05-07T14:22:04Z,88510212,10,2019-05-07T14:22:04Z,88510212,500,2019-05-07T14:21:57Z,88510213,10,2019-05-07T14:21:57Z,...,2019-06-12T15:09:12Z,88510205,07,1875,01,2019-06-12T15:09:12Z,88510207,12,2020,31
5,2019-10-09T17:22:24Z,91959769,10,2019-10-09T17:22:24Z,91959769,100,2019-10-09T17:22:24Z,91959762,10,2019-10-09T17:22:24Z,...,2019-10-09T17:22:24Z,91959761,07,1875,01,2019-10-09T17:22:24Z,91959767,12,2020,31

In [57]:
#damn = json_normalize(df['contactCommunicationAddress'][1]).columns.str.replace(".", "_").to_list()

In [58]:
# dic_flattened = [flatten(d) for d in aw]
# df = pd.DataFrame(dic_flattened)
# df

In [65]:
df.to_csv('leasedArea.csv',sep="|",quotechar='"',index=False,quoting=csv.QUOTE_ALL)

In [53]:
df.to_csv('leasedArea.csv',sep = '|')