In [2]:
%load_ext dotenv
%dotenv /home/aurora/.env
%matplotlib inline

In [3]:
import numpy as np
import pandas as pd
import datetime as dt
from google.cloud import bigquery
import re
import pymongo
import os
import warnings
from flatten_json import flatten

In [4]:
# Automated date and time
start = dt.datetime(2019,5,11)
start = start.replace(hour=0, minute=0, second=0, microsecond=0)
start = start - dt.timedelta(hours = 5, minutes = 30)
end = dt.datetime(2019,5,12)
end = end.replace(hour=0, minute=0, second=0, microsecond=0)
end = end - dt.timedelta(hours = 5, minutes = 30)
print(start,end,end-start)

2019-05-10 18:30:00 2019-05-11 18:30:00 1 day, 0:00:00

In [5]:
table_str1 = ("`hitwicketsuperstars.analytics_190927423.new_user_reference`")
print(table_str1)

`hitwicketsuperstars.analytics_190927423.new_user_reference`

In [6]:
client = bigquery.Client.from_service_account_json('/home/analytics/.secure_files/hitwicketsuperstars-f3e8c620a88c.json')
query =( f"""SELECT
*
FROM
      {table_str1}"""
       )
df = client.query(query).to_dataframe()
df.head()

,device_id,user_first_touch_timestamp,platform
0,2EFFB1C5-B5CA-48E7-B5B9-C954E3D74F10,2019-04-29 05:22:01.400000+00:00,IOS
1,41EEDC39-32BF-4396-BAE0-F161DEBE6530,2019-04-29 14:13:24.519000+00:00,IOS
2,b4494482e36a2e3bc1ecfdc0916ad2a3,2019-04-29 07:59:56.783000+00:00,ANDROID
3,f9fe6ea76a5553b8a6ddbd647611ad70,2019-04-29 09:11:33.784000+00:00,ANDROID
4,a71af85fdf36048acae89e1099ee43a0,2019-04-29 04:57:11.266000+00:00,ANDROID

In [9]:
df = df[df['platform']=='ANDROID']
df.columns = ['device_id','first_touch','platform']
df['first_touch'] = df1['first_touch'].dt.date
print(len(df))
df.head()

550726

                           device_id first_touch platform
14  336d2be8e5236c2ec4fbdde636988f6e  2019-04-30  ANDROID
15  d033c10b2e3b9d711515c3b6c1cfd2b6  2019-04-30  ANDROID
16  4a4b6e67df99d389a9d527f010a1c055  2019-04-29  ANDROID
17  b0aa896876e813cb1eb78522d26cc11b  2019-04-30  ANDROID
18  e5b79632488dff2d907915d63868e2d4  2019-04-30  ANDROID

In [11]:
device_count = df.groupby('first_touch')['device_id'].count()
device_count = device_count.to_frame().reset_index()

In [12]:
device_count.head()

  first_touch  device_id
0  1970-01-01          1
1  2010-01-01          2
2  2012-01-01          1
3  2017-01-01          2
4  2019-03-02          1

In [1]:
device_count()

NameError: name 'device_count' is not defined

In [41]:

device_count_part = e = c.loc["Oct-Dec'20":]

KeyError: "None of [['2019-03-02']] are in the [index]"

In [13]:
cursor = pymongo.MongoClient("mongodb://" + os.environ['user'] + ':' + 
                             os.environ['pass'] + '@' + os.environ['db1']  + "/?authSource=" + 
                             os.environ['dbname'])
c_users = cursor.superstars.users
aw = []
for documents in c_users.find({},{"sign_up_details":1, "created_at":1}):
    aw.append(documents)
dic_flattened = [flatten(d) for d in aw]
df1 = pd.DataFrame(dic_flattened)
users = df1[["_id","created_at","sign_up_details_device_id"]]
users.columns = ["user_id","create_time","device_id"]
print(len(users))
users.head()

128766

,user_id,create_time,device_id
0,5c702c13453bed5fa3bdba59,2019-02-22 17:06:27.769,0dbb1458df0b26c924a23c4419f79506
1,5c702f100899f358b8f31db7,2019-02-22 17:19:12.954,00da33af8422e56009693e6351ce39a1
2,5c702f1a0899f358b8f31dd6,2019-02-22 17:19:22.914,11476de18d2f222f3c18b846018d7c2b
3,5c702f9865a1f762ddc8cbe6,2019-02-22 17:21:28.152,a8fde2641d175a8c7274416f69fca69f
4,5c70308f0899f358b8f31e19,2019-02-22 17:25:35.387,3f6e334678472989053110fa7c5f2c4e

In [19]:
c_pay = cursor.superstars.payment_orders
aw = []
for documents in c_pay.find({}):
    aw.append(documents)
dic_flattened = [flatten(d) for d in aw]
df2 = pd.DataFrame(dic_flattened)
payment = df2[["_id","user_id","status","revenue_bottom_line","revenue_top_line","created_at"]]
payment = payment[payment['status']==2]
payment.columns = ["pay_id","user_id","status","revenue_bottom_line","revenue_top_line","payment_time"]
print(len(payment))
payment.head()

122

,pay_id,user_id,status,revenue_bottom_line,revenue_top_line,payment_time
0,5c7036830899f358b8f31ee8,5c702f1a0899f358b8f31dd6,2,13.993,19.99,2019-02-22 17:50:59.534
1,5c7036c465a1f762ddc8cd14,5c702f1a0899f358b8f31dd6,2,769.993,1099.99,2019-02-22 17:52:04.794
2,5c703d2965a1f762ddc8ce16,5c70308f0899f358b8f31e19,2,13.993,19.99,2019-02-22 18:19:21.882
3,5c703d630899f358b8f31f9d,5c70308f0899f358b8f31e19,2,27.993,39.99,2019-02-22 18:20:19.669
4,5c704de039b750640562a0d1,5c702f1a0899f358b8f31dd6,2,769.993,1099.99,2019-02-22 19:30:40.600

In [20]:
df5 = pd.merge(df,users,on='device_id',how='inner')
print(len(df5))
df5.head()

127186

,device_id,first_touch,platform,user_id,create_time
0,b0aa896876e813cb1eb78522d26cc11b,2019-04-30,ANDROID,5cc87c47c757b72b3a230637,2019-04-30 16:48:07.898
1,1c90a230459a792a8d21f6afb846bcc9,2019-04-30,ANDROID,5cd0950fc222ff25869ccac0,2019-05-06 20:11:59.629
2,0ab1a42431eb476d774b73bfe2ad0d08,2019-04-30,ANDROID,5cc85dde304ded1c8d2a6fb2,2019-04-30 14:38:22.048
3,86f9537ce80c5c2cbd2e68a521deabc5,2019-04-30,ANDROID,5cc7b37ac1811e2b6169bb77,2019-04-30 02:31:22.822
4,40ddf190669e8be238951c8f45eb2cc7,2019-04-30,ANDROID,5cc88ad7aaefa53d8fa16dad,2019-04-30 17:50:15.965

In [21]:
df6 = pd.merge(df5,payment,on='user_id')
print(len(df6))
df6.head()

105

,device_id,first_touch,platform,user_id,create_time,pay_id,status,revenue_bottom_line,revenue_top_line,payment_time
0,382dbc178b70f29d57446a47d339ce26,2019-04-28,ANDROID,5cc5774f9db60524bfe8b5fc,2019-04-28 09:50:07.781,5ccdc005a6267c79b8342b51,2,34.3,49.0,2019-05-04 16:38:29.257
1,d816163ad5c6456af2fb72d5494a5b8e,2019-04-28,ANDROID,5cc542242b7d5727aef33bd8,2019-04-28 06:03:16.211,5cc6b43b6b4f7624e1c0ec70,2,34.3,49.0,2019-04-29 08:22:19.405
2,67524928fcb57dbc1c3a5fc56b9ed38d,2019-04-28,ANDROID,5cc52ff17ba34e278a883721,2019-04-28 04:45:37.642,5cc6bba86b4f7624e1c11ad0,2,34.3,49.0,2019-04-29 08:54:00.241
3,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,ANDROID,5cd24142c222ff2586a41f88,2019-05-08 02:38:58.428,5cd30bb140ff8c28e6c8eb81,2,34.3,49.0,2019-05-08 17:02:41.465
4,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,ANDROID,5cd24142c222ff2586a41f88,2019-05-08 02:38:58.428,5cd34adada4d0528eda0e9f3,2,34.3,49.0,2019-05-08 21:32:10.594

In [25]:
df6.head()

,device_id,first_touch,platform,user_id,create_time,pay_id,status,revenue_bottom_line,revenue_top_line,payment_time
0,382dbc178b70f29d57446a47d339ce26,2019-04-28,ANDROID,5cc5774f9db60524bfe8b5fc,2019-04-28 09:50:07.781,5ccdc005a6267c79b8342b51,2,34.3,49.0,2019-05-04 16:38:29.257
1,d816163ad5c6456af2fb72d5494a5b8e,2019-04-28,ANDROID,5cc542242b7d5727aef33bd8,2019-04-28 06:03:16.211,5cc6b43b6b4f7624e1c0ec70,2,34.3,49.0,2019-04-29 08:22:19.405
2,67524928fcb57dbc1c3a5fc56b9ed38d,2019-04-28,ANDROID,5cc52ff17ba34e278a883721,2019-04-28 04:45:37.642,5cc6bba86b4f7624e1c11ad0,2,34.3,49.0,2019-04-29 08:54:00.241
3,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,ANDROID,5cd24142c222ff2586a41f88,2019-05-08 02:38:58.428,5cd30bb140ff8c28e6c8eb81,2,34.3,49.0,2019-05-08 17:02:41.465
4,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,ANDROID,5cd24142c222ff2586a41f88,2019-05-08 02:38:58.428,5cd34adada4d0528eda0e9f3,2,34.3,49.0,2019-05-08 21:32:10.594

In [26]:
df6.drop(['platform','user_id','create_time','pay_id','status'],axis=1,inplace=True)
#df1.drop(['device_id','flag','createtime','last_request'], axis=1,inplace = True)

In [27]:
df6.head()

,device_id,first_touch,revenue_bottom_line,revenue_top_line,payment_time
0,382dbc178b70f29d57446a47d339ce26,2019-04-28,34.3,49.0,2019-05-04 16:38:29.257
1,d816163ad5c6456af2fb72d5494a5b8e,2019-04-28,34.3,49.0,2019-04-29 08:22:19.405
2,67524928fcb57dbc1c3a5fc56b9ed38d,2019-04-28,34.3,49.0,2019-04-29 08:54:00.241
3,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,34.3,49.0,2019-05-08 17:02:41.465
4,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,34.3,49.0,2019-05-08 21:32:10.594

In [30]:
len(df6)

105

In [ ]:
df6['payment_time']=df6['payment_time'].dt.date

In [33]:
df6 = df6[(df6['payment_time']-df6['first_touch'])< ("30 days, 00:00:00")]
print(len(df6))

70

In [34]:
df6.head()

,device_id,first_touch,revenue_bottom_line,revenue_top_line,payment_time
0,382dbc178b70f29d57446a47d339ce26,2019-04-28,34.3,49.0,2019-05-04
1,d816163ad5c6456af2fb72d5494a5b8e,2019-04-28,34.3,49.0,2019-04-29
2,67524928fcb57dbc1c3a5fc56b9ed38d,2019-04-28,34.3,49.0,2019-04-29
3,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,34.3,49.0,2019-05-08
4,1075b322b4f1d1cfe298b91fa4da6883,2019-05-08,34.3,49.0,2019-05-08

In [38]:
total = df6['revenue_top_line'].sum()
total

69717.98999999999

In [ ]:
print(total/len(users))