In [9]:
%load_ext dotenv
%dotenv /home/aurora/.env
%matplotlib inline

The dotenv extension is already loaded. To reload it, use:
  %reload_ext dotenv

In [10]:
import numpy as np
import pandas as pd
import datetime as dt
from google.cloud import bigquery
import re
import pymongo
import os
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from flatten_json import flatten
#warnings.filterwarnings('ignore')

In [11]:
a = pd.read_csv('./number of active users per month according to financial years - Sheet1.csv')
df = a.iloc[1:]
df.columns = ['month','na','ra','ni','ri']
df.set_index('month',inplace = True)
df.head()

             na        ra       ni       ri
month
19-07  262500.0       0.0  37500.0      0.0
19-08  262500.0   26250.0  37500.0   4500.0
19-09  437500.0   47250.0  62500.0   8250.0
19-10  437500.0   77875.0  62500.0  14250.0
19-11  525000.0  102375.0  75000.0  19000.0

In [15]:
B = pd.read_excel('./Conversion percentage.xlsx')
df1 = B.transpose()
new_header = df1.iloc[1]
df1 = df1[2:]
df1.columns = new_header
df1
df1.columns = ['date','d1','na','ra','d2','ni','ri']
df1.drop(['d1','d2'], axis=1, inplace=True)
df1.set_index('date',inplace = True)
df1

                        na    ra     ni    ri
date
2019-07-19 00:00:00  0.003  0.06  0.006  0.09
2019-08-19 00:00:00  0.005  0.06   0.01  0.09
2019-09-19 00:00:00  0.007  0.06   0.01  0.09
2019-10-19 00:00:00  0.008  0.07  0.012  0.11
2019-11-19 00:00:00  0.008  0.07  0.012  0.11
2019-12-19 00:00:00  0.008  0.07  0.012  0.11
2019-01-20 00:00:00  0.008  0.07  0.012  0.11
2019-02-20 00:00:00  0.008  0.07  0.012  0.11
2019-03-20 00:00:00  0.008  0.07  0.012  0.11
2019-04-20 00:00:00  0.009  0.08  0.013  0.11
2019-05-20 00:00:00  0.009  0.08  0.013  0.11
2019-06-20 00:00:00  0.009  0.08  0.013  0.11
2019-07-20 00:00:00  0.009  0.08  0.013  0.11
2019-08-20 00:00:00  0.009  0.08  0.013  0.11
2019-09-20 00:00:00  0.009  0.09  0.015  0.12
Oct-Dec'20           0.009  0.09  0.015  0.12
Jan-Mar'21           0.009  0.09  0.015  0.12
Apr-Jun'21           0.009   0.1  0.015  0.13
Jul-Sept'21          0.009   0.1  0.015  0.13
Oct-Dec'21            0.01   0.1   0.02  0.14
Jan-Mar'22            0.01   0.1   0.02  0.14
Apr-Jun'22           0.012  0.11  0.022  0.14
Jul-Sept'22          0.012  0.11  0.022  0.14
Oct-Dec'22           0.018  0.12  0.028  0.16
Jan-Mar'23           0.018  0.12  0.028  0.16

In [13]:
e = df1.loc["Oct-Dec'20":]

split1 = e['na'].tolist()
split2 = e['ra'].tolist()
split3 = e['ni'].tolist()
split4 = e['ri'].tolist()

split1 = [item for item in split1 for i in range(3)]
split2 = [item for item in split2 for i in range(3)]
split3 = [item for item in split3 for i in range(3)]
split4 = [item for item in split4 for i in range(3)]

x11 = pd.DataFrame({'na':split1,'ra':split2,'ni':split3,'ri':split4})
len(x11)

30

In [59]:
x1 = df1.iloc[:15]
y = pd.concat([x1,x11],ignore_index=True)
y.head()

      na    ra     ni    ri
0  0.003  0.06  0.006  0.09
1  0.005  0.06   0.01  0.09
2  0.007  0.06   0.01  0.09
3  0.008  0.07  0.012  0.11
4  0.008  0.07  0.012  0.11

In [63]:
from datetime import timedelta, date
def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)
date_list = []
start_dt = date(19,7,1)
end_dt = date(23,3,30)
for dt in daterange(start_dt, end_dt):
    date_list.append(dt.strftime("%Y-%m"))
    
xy = pd.DataFrame({'months': date_list})
xy.drop_duplicates('months',inplace = True)
xy.reset_index(drop=True, inplace=True)

In [66]:
z = pd.merge(y, xy , left_index=True,right_index = True)
z.set_index('months',inplace=True)
len(z)

45

In [68]:
c3 = pd.DataFrame(df.values*z.values, columns=df.columns, index=df.index)

            na       ra       ni       ri
month
19-07    787.5        0      225        0
19-08   1312.5     1575      375      405
19-09   3062.5     2835      625    742.5
19-10     3500  5451.25      750   1567.5
19-11     4200  7166.25      900     2090
19-12     4200   8942.5      900  2681.25
20-01     4900  10381.9     1050  3148.75
20-02     4900  12127.5     1050     3685
20-03     4900  13628.1     1050   4097.5
20-04     9450    16905     1950  4441.25
20-05    11025    22470     2275  5706.25
20-06    11025    28735     2275  7163.75
20-07    11025    33635     2275  8401.25
20-08    11025    37520     2275  9391.25
20-09    11025  46029.4     2625    11175
20-10    13125  49297.5  3124.99    11970
20-11    13125  54678.7  3124.99  13157.5
20-12    13125  59561.2  3124.99    14145
21-01    13125  63538.1  3124.99  15007.5
21-02    13125  67147.5  3124.99    15775
21-03    13125  70507.5  3124.99    16495
21-04    26250  81958.3  6249.99  18606.2
21-05    26250   105510  6249.99  23543.5
21-06    26250   125971  6249.99  27863.3
21-07    18375   141940  4374.99  31641.4
21-08    18375   145162  4374.99  32456.6
21-09    18375   148590  4374.99  33309.7
21-10    17500   153825     5000  36831.6
21-11    17500   156056     5000    36957
21-12    17500   159702     5000  37073.7
22-01  20416.7   163931  5833.32    37482
22-02  20416.7   171937  5833.32  38995.8
22-03  20416.7   179652  5833.32  40626.2
22-04    52500   205782    13750  42198.3
22-05    52500   249929    13750  51245.8
22-06    52500   288333    13750  59307.4
22-07    28000   319037  7333.33  66377.5
22-08    28000   315892  7333.33  65951.6
22-09    28000   314673  7333.33  65817.4
22-10    36750   347725  8166.65  75466.6
22-11    36750   350175  8166.65  75133.3
22-12    36750   355775  8166.65  74866.6
23-01    36750   362250  8166.65  75199.9
23-02    36750   368900  8166.65  76099.9
23-03    36750   375900  8166.65  77533.2

In [73]:
c4 = (c3.sum(axis=1)).round()
c4 = c4.to_frame().reset_index()
c4.set_index('month',inplace=True)
d = pd.merge(c3, c4, left_index=True, right_index=True)
d.columns = ['new android','retained android','new iOS','retained iOS','Total']
d
# c4.columns = ['index','totals']
# c4 = c4[['totals']]
# c4 = c4.set_index(z.index)

      new android retained android  new iOS retained iOS     Total
month
19-07       787.5                0      225            0    1012.0
19-08      1312.5             1575      375          405    3668.0
19-09      3062.5             2835      625        742.5    7265.0
19-10        3500          5451.25      750       1567.5   11269.0
19-11        4200          7166.25      900         2090   14356.0
19-12        4200           8942.5      900      2681.25   16724.0
20-01        4900          10381.9     1050      3148.75   19481.0
20-02        4900          12127.5     1050         3685   21762.0
20-03        4900          13628.1     1050       4097.5   23676.0
20-04        9450            16905     1950      4441.25   32746.0
20-05       11025            22470     2275      5706.25   41476.0
20-06       11025            28735     2275      7163.75   49199.0
20-07       11025            33635     2275      8401.25   55336.0
20-08       11025            37520     2275      9391.25   60211.0
20-09       11025          46029.4     2625        11175   70854.0
20-10       13125          49297.5  3124.99        11970   77517.0
20-11       13125          54678.7  3124.99      13157.5   84086.0
20-12       13125          59561.2  3124.99        14145   89956.0
21-01       13125          63538.1  3124.99      15007.5   94796.0
21-02       13125          67147.5  3124.99        15775   99172.0
21-03       13125          70507.5  3124.99        16495  103252.0
21-04       26250          81958.3  6249.99      18606.2  133065.0
21-05       26250           105510  6249.99      23543.5  161554.0
21-06       26250           125971  6249.99      27863.3  186334.0
21-07       18375           141940  4374.99      31641.4  196331.0
21-08       18375           145162  4374.99      32456.6  200369.0
21-09       18375           148590  4374.99      33309.7  204649.0
21-10       17500           153825     5000      36831.6  213157.0
21-11       17500           156056     5000        36957  215513.0
21-12       17500           159702     5000      37073.7  219276.0
22-01     20416.7           163931  5833.32        37482  227663.0
22-02     20416.7           171937  5833.32      38995.8  237183.0
22-03     20416.7           179652  5833.32      40626.2  246528.0
22-04       52500           205782    13750      42198.3  314231.0
22-05       52500           249929    13750      51245.8  367425.0
22-06       52500           288333    13750      59307.4  413890.0
22-07       28000           319037  7333.33      66377.5  420747.0
22-08       28000           315892  7333.33      65951.6  417177.0
22-09       28000           314673  7333.33      65817.4  415824.0
22-10       36750           347725  8166.65      75466.6  468108.0
22-11       36750           350175  8166.65      75133.3  470225.0
22-12       36750           355775  8166.65      74866.6  475558.0
23-01       36750           362250  8166.65      75199.9  482366.0
23-02       36750           368900  8166.65      76099.9  489916.0
23-03       36750           375900  8166.65      77533.2  498350.0